[2025-09-22T10:04:33.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-22T10:04:33.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.run_dbt manual__2025-09-22T10:04:30.383558+00:00 [queued]>
[2025-09-22T10:04:33.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.run_dbt manual__2025-09-22T10:04:30.383558+00:00 [queued]>
[2025-09-22T10:04:33.608+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-22T10:04:33.626+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-09-22 10:04:30.383558+00:00
[2025-09-22T10:04:33.635+0000] {standard_task_runner.py:64} INFO - Started process 2053 to run task
[2025-09-22T10:04:33.640+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'run_dbt', 'manual__2025-09-22T10:04:30.383558+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/air_quality_pipeline.py', '--cfg-path', '/tmp/tmppi23vxds']
[2025-09-22T10:04:33.643+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_dbt
[2025-09-22T10:04:33.666+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-22T10:04:33.722+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.run_dbt manual__2025-09-22T10:04:30.383558+00:00 [running]> on host bb39335e5c99
[2025-09-22T10:04:34.031+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T10:04:30.383558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-22T10:04:30.383558+00:00'
[2025-09-22T10:04:34.033+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-22T10:04:40.693+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-22T10:04:40.694+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/orchestration/air_quality_pipeline.py", line 23, in run_dbt
    subprocess.run(
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', 'run', '--project-dir', '/opt/airflow/data_transformation/air_quality_dbt', '--profiles-dir', '/opt/airflow/data_transformation/air_quality_dbt']' returned non-zero exit status 1.
[2025-09-22T10:04:40.713+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=air_quality_pipeline, task_id=run_dbt, run_id=manual__2025-09-22T10:04:30.383558+00:00, execution_date=20250922T100430, start_date=20250922T100433, end_date=20250922T100440
[2025-09-22T10:04:40.732+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task run_dbt (Command '['dbt', 'run', '--project-dir', '/opt/airflow/data_transformation/air_quality_dbt', '--profiles-dir', '/opt/airflow/data_transformation/air_quality_dbt']' returned non-zero exit status 1.; 2053)
[2025-09-22T10:04:40.768+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-22T10:04:40.795+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-22T10:04:40.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
